services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - card-game-network

  cli:
    build:
      context: .
      dockerfile: Dockerfile.cli
    depends_on:
      - app
    environment:
      - SPRING_PROFILES_ACTIVE=cli
      - API_BASE_URL=http://app:8080/api
    networks:
      - card-game-network
    stdin_open: true  # docker run -i
    tty: true        # docker run -t

  postgres:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=carddeckgame
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - card-game-network

networks:
  card-game-network:
    driver: bridge

volumes:
  postgres-data: